name = "dreams5-onboarding-agent"
main = "dreams5-onboarding-agent/dist/index.js"
compatibility_date = "2024-05-01"

[build]
command = "npm install --prefix dreams5-onboarding-agent && npm run build --prefix dreams5-onboarding-agent"

# Static assets served by Worker (free plan)
[assets]
directory = "dreams5-onboarding-agent/public"
binding = "ASSETS"

# Durable Object — per-tenant state machine
[[durable_objects.bindings]]
name = "ONBOARD_BRAIN"
class_name = "OnboardBrain"

# D1 (relational source of truth)
[[d1_databases]]
binding = "DB"
database_name = "dreams5_db"
database_id = "REPLACE_WITH_DB_ID"

# KV — config, copy, flags
[[kv_namespaces]]
binding = "KV_CONFIG"
id = "REPLACE_WITH_KV_ID"

[vars]
APP_NAME = "DREAMS5 Onboarding Agent"
GREENLIGHT_MIN_REQUIRED = "12"

[[migrations]]
tag = "v1"
new_classes = ["OnboardBrain"]

[env.dev]
name = "dreams5-onboarding-agent-dev"
account_id = "REPLACE_WITH_ACCOUNT_ID"
route = ""
