name = "dreams5-onboarding-agent"
compatibility_date = "2024-05-01"
type = "javascript"

[build]
command = "npm install --prefix dreams5-onboarding-agent && npm run build --prefix dreams5-onboarding-agent"

[build.upload]
main = "dreams5-onboarding-agent/dist/index.js"
format = "modules"

[[rules]]
globs = ["dreams5-onboarding-agent/dist/**/*.js"]
type = "ESModule"

# Optional static site (serves files from ./public)
[site]
bucket = "dreams5-onboarding-agent/public"

# Durable Object — per-tenant state machine
[[durable_objects.bindings]]
name = "ONBOARD_BRAIN"
class_name = "OnboardBrain"

# D1 (relational source of truth)
[[d1_databases]]
binding = "DB"
database_name = "dreams5_db"
database_id = "REPLACE_WITH_DB_ID"

# KV — config, copy, flags
[[kv_namespaces]]
binding = "KV_CONFIG"
id = "REPLACE_WITH_KV_ID"

[vars]
APP_NAME = "DREAMS5 Onboarding Agent"
GREENLIGHT_MIN_REQUIRED = "12"

[env.dev]
name = "dreams5-onboarding-agent-dev"
account_id = "REPLACE_WITH_ACCOUNT_ID"
route = ""
