name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install
        run: npm ci
      - name: Typecheck
        run: npm run typecheck
      - name: Miniflare smoke test
        run: |
          npx miniflare --source=src/index.ts &
          sleep 2
          curl -f http://127.0.0.1:8787/ || (echo 'smoke test failed' && exit 1)
